# Generated by Django 5.2.6 on 2025-11-01 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="card_provider",
            field=models.CharField(
                choices=[
                    ("internal", "Internal"),
                    ("flutterwave", "Flutterwave"),
                    ("sudo", "Sudo"),
                    ("stripe", "Stripe"),
                    ("paystack", "Paystack"),
                ],
                help_text="Provider managing this card",
                max_length=20,
            ),
        ),
    ]
