# Generated by Django 5.2.6 on 2025-11-06 11:25

import apps.cards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0002_alter_card_card_provider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="last_daily_reset",
            field=models.DateField(default=apps.cards.models.get_current_date),
        ),
        migrations.AlterField(
            model_name="card",
            name="last_monthly_reset",
            field=models.DateField(default=apps.cards.models.get_current_date),
        ),
    ]
