# Generated by Django 5.2.6 on 2025-11-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0003_alter_card_last_daily_reset_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
