# Generated by Django 5.2.6 on 2025-10-19 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="KYC",
        ),
    ]
