# Generated by Django 5.2.6 on 2025-11-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_alter_country_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
