# Generated by Django 5.2.6 on 2025-10-19 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="amlcheck",
            name="fraud_score",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Fraud risk score from external fraud detection API",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="kycverification",
            name="is_politically_exposed",
            field=models.BooleanField(
                default=False, help_text="PEP (Politically Exposed Person) - AML flag"
            ),
        ),
        migrations.AddField(
            model_name="kycverification",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="kycverification",
            name="provider_name",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="kycverification",
            name="provider_reference_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="kycverification",
            name="provider_status",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="kycverification",
            name="verification_method",
            field=models.CharField(
                choices=[
                    ("manual", "Manual Review"),
                    ("automated", "Automated"),
                    ("hybrid", "Hybrid"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="kycverification",
            name="webhook_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
