# Generated by Django 5.2.6 on 2025-10-19 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0002_amlcheck_fraud_score_and_more"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="amlcheck",
            new_name="compliance__user_id_7e5985_idx",
            old_name="aml_checks_user_id_1b91e5_idx",
        ),
        migrations.RenameIndex(
            model_name="amlcheck",
            new_name="compliance__risk_le_0fa059_idx",
            old_name="aml_checks_risk_le_9531ad_idx",
        ),
        migrations.RenameIndex(
            model_name="amlcheck",
            new_name="compliance__transac_ca5859_idx",
            old_name="aml_checks_transac_bd478e_idx",
        ),
        migrations.RenameIndex(
            model_name="compliancereport",
            new_name="compliance__report__65f853_idx",
            old_name="compliance__report__86af4a_idx",
        ),
        migrations.RenameIndex(
            model_name="kycverification",
            new_name="compliance__user_id_3462b8_idx",
            old_name="kyc_verific_user_id_8bfe00_idx",
        ),
        migrations.RenameIndex(
            model_name="kycverification",
            new_name="compliance__status_22d5c7_idx",
            old_name="kyc_verific_status_8cf549_idx",
        ),
        migrations.RenameIndex(
            model_name="kycverification",
            new_name="compliance__documen_a6ebff_idx",
            old_name="kyc_verific_documen_17ce21_idx",
        ),
        migrations.RenameIndex(
            model_name="sanctionsscreening",
            new_name="compliance__user_id_e5a606_idx",
            old_name="sanctions_s_user_id_a6e3eb_idx",
        ),
        migrations.RenameIndex(
            model_name="sanctionsscreening",
            new_name="compliance__is_matc_de914e_idx",
            old_name="sanctions_s_is_matc_0d71d2_idx",
        ),
        migrations.RenameIndex(
            model_name="transactionmonitoring",
            new_name="compliance__user_id_2cdca7_idx",
            old_name="transaction_user_id_36a4a3_idx",
        ),
        migrations.RenameIndex(
            model_name="transactionmonitoring",
            new_name="compliance__transac_c0ada2_idx",
            old_name="transaction_transac_b51dc6_idx",
        ),
        migrations.RenameIndex(
            model_name="transactionmonitoring",
            new_name="compliance__risk_le_cde9be_idx",
            old_name="transaction_risk_le_06f322_idx",
        ),
        migrations.RenameIndex(
            model_name="transactionmonitoring",
            new_name="compliance__alert_t_086f00_idx",
            old_name="transaction_alert_t_be89b2_idx",
        ),
        migrations.AlterModelTable(
            name="amlcheck",
            table=None,
        ),
        migrations.AlterModelTable(
            name="compliancereport",
            table=None,
        ),
        migrations.AlterModelTable(
            name="kycdocument",
            table=None,
        ),
        migrations.AlterModelTable(
            name="kycverification",
            table=None,
        ),
        migrations.AlterModelTable(
            name="sanctionsscreening",
            table=None,
        ),
        migrations.AlterModelTable(
            name="transactionmonitoring",
            table=None,
        ),
    ]
