# Generated by Django 5.2.6 on 2025-10-31 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "compliance",
            "0003_rename_aml_checks_user_id_1b91e5_idx_compliance__user_id_7e5985_idx_and_more",
        ),
        ("profiles", "0003_alter_country_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kycverification",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="kyc_verifications",
                to="profiles.country",
            ),
        ),
        migrations.AlterField(
            model_name="kycverification",
            name="document_issuing_country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="issuer_kyc_verifications",
                to="profiles.country",
            ),
        ),
    ]
