# Generated by Django 5.2.6 on 2025-11-04 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0004_alter_kycverification_country_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="kycverification",
            name="selfie_image",
            field=models.ImageField(null=True, upload_to="kyc_selfies/"),
        ),
    ]
