# Generated by Django 5.2.6 on 2025-10-19 20:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "template_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("payment", "Payment"),
                            ("loan", "Loan"),
                            ("card", "Card"),
                            ("kyc", "KYC/Compliance"),
                            ("bill", "Bill Payment"),
                            ("account", "Account"),
                            ("security", "Security"),
                            ("promotion", "Promotion"),
                            ("system", "System"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "title_template",
                    models.CharField(
                        help_text="Use {{variable}} for substitution", max_length=200
                    ),
                ),
                (
                    "message_template",
                    models.TextField(help_text="Use {{variable}} for substitution"),
                ),
                (
                    "action_url_template",
                    models.CharField(
                        blank=True,
                        help_text="Use {{variable}} for substitution",
                        max_length=500,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "notification_templates",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(null=True)),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("payment", "Payment"),
                            ("loan", "Loan"),
                            ("card", "Card"),
                            ("kyc", "KYC/Compliance"),
                            ("bill", "Bill Payment"),
                            ("account", "Account"),
                            ("security", "Security"),
                            ("promotion", "Promotion"),
                            ("system", "System"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("is_read", models.BooleanField(db_index=True, default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("sent_via_push", models.BooleanField(default=False)),
                ("push_sent_at", models.DateTimeField(blank=True, null=True)),
                ("sent_via_websocket", models.BooleanField(default=False)),
                ("websocket_sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "related_object_type",
                    models.CharField(
                        blank=True,
                        help_text="Model name: Payment, Loan, Card, etc.",
                        max_length=50,
                    ),
                ),
                (
                    "related_object_id",
                    models.CharField(
                        blank=True,
                        help_text="UUID or ID of related object",
                        max_length=100,
                    ),
                ),
                (
                    "action_url",
                    models.CharField(
                        blank=True,
                        help_text="Deep link or URL to open when notification is tapped",
                        max_length=500,
                    ),
                ),
                (
                    "action_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional data for handling notification action",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata for the notification",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Optional expiration date for time-sensitive notifications",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="notificatio_user_id_05b4bc_idx",
                    ),
                    models.Index(
                        fields=["user", "is_read", "-created_at"],
                        name="notificatio_user_id_f2ad08_idx",
                    ),
                    models.Index(
                        fields=["notification_type", "-created_at"],
                        name="notificatio_notific_d8746a_idx",
                    ),
                ],
            },
        ),
    ]
