# Generated by Django 5.2.6 on 2025-10-19 21:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            # Database operations
            database_operations=[
                migrations.RunSQL(
                    sql="DROP TABLE IF EXISTS notification_templates CASCADE;",
                    reverse_sql="",
                ),
                migrations.RunSQL(
                    sql="""
                    CREATE TABLE "notifications_notificationtemplate" (
                        "id" uuid NOT NULL PRIMARY KEY,
                        "created_at" timestamp with time zone NOT NULL,
                        "updated_at" timestamp with time zone NOT NULL,
                        "deleted_at" timestamp with time zone NULL,
                        "name" varchar(100) NOT NULL UNIQUE,
                        "notification_type" varchar(20) NOT NULL,
                        "priority" varchar(10) NOT NULL,
                        "title_template" varchar(200) NOT NULL,
                        "message_template" text NOT NULL,
                        "action_url_template" varchar(500) NOT NULL,
                        "is_active" boolean NOT NULL
                    );
                    """,
                    reverse_sql="DROP TABLE IF EXISTS notifications_notificationtemplate;",
                ),
            ],
            # State operations (what Django thinks happened)
            state_operations=[
                migrations.RemoveField(
                    model_name="notificationtemplate",
                    name="template_id",
                ),
                migrations.AddField(
                    model_name="notificationtemplate",
                    name="deleted_at",
                    field=models.DateTimeField(null=True),
                ),
                migrations.AlterField(
                    model_name="notificationtemplate",
                    name="id",
                    field=models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                migrations.AlterModelTable(
                    name="notificationtemplate",
                    table=None,
                ),
            ],
        ),
    ]
