# Generated by Django 5.2.6 on 2025-11-02 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_remove_notificationtemplate_template_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="related_object_id",
            field=models.CharField(
                blank=True,
                help_text="UUID or ID of related object",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="related_object_type",
            field=models.CharField(
                blank=True,
                help_text="Model name: Payment, Loan, Card, etc.",
                max_length=50,
                null=True,
            ),
        ),
    ]
