# Generated by Django 5.2.6 on 2025-11-02 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_alter_notification_related_object_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="action_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Additional data for handling notification action",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="action_url",
            field=models.CharField(
                blank=True,
                help_text="Deep link or URL to open when notification is tapped",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Additional metadata for the notification",
                null=True,
            ),
        ),
    ]
