# Generated by Django 5.2.6 on 2025-11-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0004_alter_notification_action_data_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="notificationtemplate",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
