# Generated by Django 5.2.6 on 2025-11-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0005_alter_notification_deleted_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("payment", "Payment"),
                    ("transfer", "Transfer"),
                    ("loan", "Loan"),
                    ("investment", "Investment"),
                    ("card", "Card"),
                    ("kyc", "KYC/Compliance"),
                    ("bill", "Bill Payment"),
                    ("wallet", "Wallet"),
                    ("account", "Account"),
                    ("security", "Security"),
                    ("promotion", "Promotion"),
                    ("system", "System"),
                    ("other", "Other"),
                ],
                db_index=True,
                default="other",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="notificationtemplate",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("payment", "Payment"),
                    ("transfer", "Transfer"),
                    ("loan", "Loan"),
                    ("investment", "Investment"),
                    ("card", "Card"),
                    ("kyc", "KYC/Compliance"),
                    ("bill", "Bill Payment"),
                    ("wallet", "Wallet"),
                    ("account", "Account"),
                    ("security", "Security"),
                    ("promotion", "Promotion"),
                    ("system", "System"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
    ]
