# Generated by Django 6.0 on 2026-01-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(help_text='Name of the model that was deleted.', max_length=100)),
                ('record_id', models.CharField(help_text='Primary key of the deleted record (UUID or Int).', max_length=255)),
                ('data', models.JSONField(help_text='Serialized data of the deleted record.')),
                ('deleted_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of deletion.')),
            ],
            options={
                'indexes': [models.Index(fields=['model_name', 'record_id'], name='common_dele_model_n_c49967_idx')],
            },
        ),
    ]
