# Generated by Django 5.2.6 on 2025-10-18 23:47

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="invoice",
            new_name="payments_in_user_id_6b50b6_idx",
            old_name="invoices_user_id_b72724_idx",
        ),
        migrations.RenameIndex(
            model_name="invoice",
            new_name="payments_in_invoice_3fa711_idx",
            old_name="invoices_invoice_7778bc_idx",
        ),
        migrations.RenameIndex(
            model_name="invoice",
            new_name="payments_in_status_44f3d3_idx",
            old_name="invoices_status_36d06c_idx",
        ),
        migrations.RenameIndex(
            model_name="invoice",
            new_name="payments_in_custome_515036_idx",
            old_name="invoices_custome_b6c506_idx",
        ),
        migrations.RenameIndex(
            model_name="merchantapikey",
            new_name="payments_me_user_id_330971_idx",
            old_name="merchant_ap_user_id_798081_idx",
        ),
        migrations.RenameIndex(
            model_name="merchantapikey",
            new_name="payments_me_key_fe32cc_idx",
            old_name="merchant_ap_key_7bf2d7_idx",
        ),
        migrations.RenameIndex(
            model_name="payment",
            new_name="payments_pa_merchan_590a46_idx",
            old_name="payments_merchan_a20116_idx",
        ),
        migrations.RenameIndex(
            model_name="payment",
            new_name="payments_pa_referen_75358f_idx",
            old_name="payments_referen_2b1f06_idx",
        ),
        migrations.RenameIndex(
            model_name="payment",
            new_name="payments_pa_status_21ed42_idx",
            old_name="payments_status_db6b16_idx",
        ),
        migrations.RenameIndex(
            model_name="paymentlink",
            new_name="payments_pa_user_id_9aba45_idx",
            old_name="payment_lin_user_id_6518e6_idx",
        ),
        migrations.RenameIndex(
            model_name="paymentlink",
            new_name="payments_pa_slug_bc7665_idx",
            old_name="payment_lin_slug_24947e_idx",
        ),
        migrations.RenameIndex(
            model_name="paymentlink",
            new_name="payments_pa_status_fc639d_idx",
            old_name="payment_lin_status_71eef8_idx",
        ),
        migrations.AlterField(
            model_name="paymentlink",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False, max_length=100, populate_from="title", unique=True
            ),
        ),
        migrations.AlterModelTable(
            name="invoice",
            table=None,
        ),
        migrations.AlterModelTable(
            name="invoiceitem",
            table=None,
        ),
        migrations.AlterModelTable(
            name="merchantapikey",
            table=None,
        ),
        migrations.AlterModelTable(
            name="payment",
            table=None,
        ),
        migrations.AlterModelTable(
            name="paymentlink",
            table=None,
        ),
    ]
