# Generated by Django 5.2.6 on 2025-10-19 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="faq",
            options={"ordering": ["order", "-created_at"]},
        ),
        migrations.RenameIndex(
            model_name="faq",
            new_name="support_faq_categor_12e075_idx",
            old_name="support_faq_categor_696325_idx",
        ),
        migrations.RenameIndex(
            model_name="faq",
            new_name="support_faq_is_publ_6e98f6_idx",
            old_name="support_faq_is_publ_c5b5a7_idx",
        ),
        migrations.RenameIndex(
            model_name="supportticket",
            new_name="support_sup_user_id_1a6c3e_idx",
            old_name="support_tic_user_id_057736_idx",
        ),
        migrations.RenameIndex(
            model_name="supportticket",
            new_name="support_sup_status_c67c70_idx",
            old_name="support_tic_status_c8e2c5_idx",
        ),
        migrations.RenameIndex(
            model_name="supportticket",
            new_name="support_sup_categor_65532e_idx",
            old_name="support_tic_categor_276175_idx",
        ),
        migrations.RenameIndex(
            model_name="supportticket",
            new_name="support_sup_assigne_87974a_idx",
            old_name="support_tic_assigne_9415d6_idx",
        ),
        migrations.RenameIndex(
            model_name="supportticket",
            new_name="support_sup_created_f4f0fe_idx",
            old_name="support_tic_created_76a570_idx",
        ),
        migrations.RenameIndex(
            model_name="ticketmessage",
            new_name="support_tic_ticket__0cd9bd_idx",
            old_name="ticket_mess_ticket__80bcb6_idx",
        ),
        migrations.RenameIndex(
            model_name="ticketmessage",
            new_name="support_tic_is_read_7576e7_idx",
            old_name="ticket_mess_is_read_1c2101_idx",
        ),
        migrations.AlterModelTable(
            name="cannedresponse",
            table=None,
        ),
        migrations.AlterModelTable(
            name="faq",
            table=None,
        ),
        migrations.AlterModelTable(
            name="supportticket",
            table=None,
        ),
        migrations.AlterModelTable(
            name="ticketattachment",
            table=None,
        ),
        migrations.AlterModelTable(
            name="ticketescalation",
            table=None,
        ),
        migrations.AlterModelTable(
            name="ticketmessage",
            table=None,
        ),
    ]
