# Generated by Django 5.2.6 on 2025-09-28 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
        ("wallets", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="from_wallet_id",
            new_name="from_wallet",
        ),
        migrations.RenameField(
            model_name="transactiondispute",
            old_name="type",
            new_name="dispute_type",
        ),
        migrations.RenameIndex(
            model_name="transaction",
            new_name="transaction_from_wa_8257c5_idx",
            old_name="transaction_from_wa_982066_idx",
        ),
        migrations.RemoveField(
            model_name="transactionhold",
            name="is_released",
        ),
        migrations.RemoveField(
            model_name="transactionhold",
            name="wallet_id",
        ),
        migrations.AddField(
            model_name="transactionhold",
            name="wallet",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="holds",
                to="wallets.wallet",
            ),
        ),
    ]
