# Generated by Django 5.2.6 on 2025-09-28 21:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_rename_from_wallet_id_transaction_from_wallet_and_more"),
        ("wallets", "0003_remove_wallet_unique_default_wallet_per_currency_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="transaction",
            name="transaction_type_a267f0_idx",
        ),
        migrations.RemoveIndex(
            model_name="transaction",
            name="transaction_from_wa_8257c5_idx",
        ),
        migrations.RemoveIndex(
            model_name="transaction",
            name="transaction_to_wall_b17f16_idx",
        ),
        migrations.RenameField(
            model_name="transaction",
            old_name="type",
            new_name="transaction_type",
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["transaction_type", "created_at"],
                name="transaction_transac_ed79fb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["from_wallet"], name="transaction_from_wa_8257c5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["to_wallet"], name="transaction_to_wall_b17f16_idx"
            ),
        ),
    ]
