# Generated by Django 5.2.6 on 2025-10-04 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0001_initial"),
        (
            "transactions",
            "0003_remove_transaction_transaction_type_a267f0_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="card",
            field=models.ForeignKey(
                blank=True,
                help_text="Card used for this transaction (if applicable)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="cards.card",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="merchant_category",
            field=models.CharField(
                blank=True,
                help_text="Merchant category code (MCC)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="merchant_name",
            field=models.CharField(
                blank=True,
                help_text="Merchant name for card transactions",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="sender_account_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="sender_account_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="sender_bank_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="transaction_location",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Transaction location (city, country, coordinates)",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="virtual_account_id",
            field=models.UUIDField(
                blank=True, help_text="Virtual account used for this deposit", null=True
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("transfer", "Transfer"),
                    ("deposit", "Deposit"),
                    ("withdrawal", "Withdrawal"),
                    ("payment", "Payment"),
                    ("refund", "Refund"),
                    ("fee", "Fee"),
                    ("hold", "Hold"),
                    ("release", "Release"),
                    ("split_payment", "Split Payment"),
                    ("recurring_payment", "Recurring Payment"),
                    ("qr_payment", "QR Payment"),
                    ("virtual_card", "Virtual Card"),
                    ("adjustment", "Adjustment"),
                    ("card_purchase", "Card Purchase"),
                    ("card_withdrawal", "Card ATM Withdrawal"),
                    ("card_refund", "Card Refund"),
                    ("card_reversal", "Card Reversal"),
                    ("card_fund", "Card Funding"),
                ],
                max_length=20,
            ),
        ),
    ]
