# Generated by Django 5.2.6 on 2025-10-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "transactions",
            "0004_transaction_card_transaction_merchant_category_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("transfer", "Transfer"),
                    ("deposit", "Deposit"),
                    ("withdrawal", "Withdrawal"),
                    ("payment", "Payment"),
                    ("refund", "Refund"),
                    ("fee", "Fee"),
                    ("hold", "Hold"),
                    ("release", "Release"),
                    ("split_payment", "Split Payment"),
                    ("recurring_payment", "Recurring Payment"),
                    ("qr_payment", "QR Payment"),
                    ("virtual_card", "Virtual Card"),
                    ("adjustment", "Adjustment"),
                    ("card_purchase", "Card Purchase"),
                    ("card_withdrawal", "Card ATM Withdrawal"),
                    ("card_refund", "Card Refund"),
                    ("card_reversal", "Card Reversal"),
                    ("card_fund", "Card Funding"),
                    ("bill_payment", "Bill Payment"),
                ],
                max_length=20,
            ),
        ),
    ]
