# Generated by Django 5.2.6 on 2025-11-01 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0005_alter_transaction_transaction_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="direction",
            field=models.CharField(
                choices=[
                    ("inbound", "Inbound"),
                    ("outbound", "Outbound"),
                    ("internal", "Internal"),
                ],
                default="internal",
                max_length=20,
            ),
        ),
    ]
