# Generated by Django 5.2.6 on 2025-11-02 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0006_alter_transaction_direction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("transfer", "Transfer"),
                    ("deposit", "Deposit"),
                    ("withdrawal", "Withdrawal"),
                    ("payment", "Payment"),
                    ("refund", "Refund"),
                    ("fee", "Fee"),
                    ("hold", "Hold"),
                    ("release", "Release"),
                    ("split_payment", "Split Payment"),
                    ("recurring_payment", "Recurring Payment"),
                    ("qr_payment", "QR Payment"),
                    ("virtual_card", "Virtual Card"),
                    ("adjustment", "Adjustment"),
                    ("card_purchase", "Card Purchase"),
                    ("card_withdrawal", "Card ATM Withdrawal"),
                    ("card_refund", "Card Refund"),
                    ("card_reversal", "Card Reversal"),
                    ("card_fund", "Card Funding"),
                    ("bill_payment", "Bill Payment"),
                    ("loan_payment", "Loan Payment"),
                    ("loan_repayment", "Loan Repayment"),
                    ("loan_fee", "Loan Fee"),
                    ("loan_interest", "Loan Interest"),
                    ("loan_penalty", "Loan Penalty"),
                    ("investment", "Investment"),
                    ("investment_repayment", "Investment Repayment"),
                    ("investment_fee", "Investment Fee"),
                    ("investment_interest", "Investment Interest"),
                    ("investment_penalty", "Investment Penalty"),
                    ("investment_payout", "Investment Payout"),
                ],
                max_length=20,
            ),
        ),
    ]
