# Generated by Django 5.2.6 on 2025-10-19 01:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("transactions", "0005_alter_transaction_transaction_type"),
        ("wallets", "0005_delete_virtualcard"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InvestmentPortfolio",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(null=True)),
                (
                    "total_invested",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "total_active_investments",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "total_returns_earned",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "total_matured_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                ("active_investments_count", models.PositiveIntegerField(default=0)),
                ("matured_investments_count", models.PositiveIntegerField(default=0)),
                ("total_investments_count", models.PositiveIntegerField(default=0)),
                (
                    "average_return_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Average return rate across all investments",
                        max_digits=5,
                    ),
                ),
                ("last_calculated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="investment_portfolio",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "investment_portfolios",
            },
        ),
        migrations.CreateModel(
            name="InvestmentProduct",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(null=True)),
                (
                    "product_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("fixed_deposit", "Fixed Deposit"),
                            ("savings_plan", "Savings Plan"),
                            ("mutual_fund", "Mutual Fund"),
                            ("bond", "Bond"),
                            ("stock", "Stock"),
                            ("treasury_bill", "Treasury Bill"),
                            ("money_market", "Money Market"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("min_amount", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "max_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "interest_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Annual interest rate in percentage",
                        max_digits=5,
                    ),
                ),
                (
                    "payout_frequency",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("semi_annually", "Semi-Annually"),
                            ("annually", "Annually"),
                            ("at_maturity", "At Maturity"),
                        ],
                        default="at_maturity",
                        max_length=20,
                    ),
                ),
                (
                    "min_duration_days",
                    models.PositiveIntegerField(
                        help_text="Minimum investment duration in days"
                    ),
                ),
                (
                    "max_duration_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum investment duration in days (null for flexible)",
                        null=True,
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low Risk"),
                            ("medium", "Medium Risk"),
                            ("high", "High Risk"),
                            ("very_high", "Very High Risk"),
                        ],
                        default="low",
                        max_length=20,
                    ),
                ),
                (
                    "is_capital_guaranteed",
                    models.BooleanField(
                        default=True, help_text="Is principal amount guaranteed?"
                    ),
                ),
                ("allows_early_liquidation", models.BooleanField(default=False)),
                (
                    "early_liquidation_penalty",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Penalty percentage for early liquidation",
                        max_digits=5,
                    ),
                ),
                ("allows_auto_renewal", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "available_slots",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Limited slots available (null for unlimited)",
                        null=True,
                    ),
                ),
                ("slots_taken", models.PositiveIntegerField(default=0)),
                ("terms_and_conditions", models.TextField(blank=True)),
                (
                    "benefits",
                    models.JSONField(
                        blank=True, default=list, help_text="List of benefits"
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="investment_products",
                        to="wallets.currency",
                    ),
                ),
            ],
            options={
                "db_table": "investment_products",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Investment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(null=True)),
                (
                    "investment_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "principal_amount",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                (
                    "interest_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Interest rate at time of investment (locked)",
                        max_digits=5,
                    ),
                ),
                (
                    "duration_days",
                    models.PositiveIntegerField(
                        help_text="Investment duration in days"
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("maturity_date", models.DateTimeField()),
                ("actual_maturity_date", models.DateTimeField(blank=True, null=True)),
                (
                    "expected_returns",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Expected total returns at maturity",
                        max_digits=20,
                    ),
                ),
                (
                    "actual_returns",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Actual returns earned so far",
                        max_digits=20,
                    ),
                ),
                (
                    "total_payout",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total amount paid out (principal + returns)",
                        max_digits=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("matured", "Matured"),
                            ("liquidated", "Liquidated (Early Exit)"),
                            ("cancelled", "Cancelled"),
                            ("renewed", "Renewed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("auto_renew", models.BooleanField(default=False)),
                ("liquidation_date", models.DateTimeField(blank=True, null=True)),
                (
                    "liquidation_penalty",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "investment_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="investments_created",
                        to="transactions.transaction",
                    ),
                ),
                (
                    "payout_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="investments_paid_out",
                        to="transactions.transaction",
                    ),
                ),
                (
                    "renewed_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="renewals",
                        to="investments.investment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="investments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        help_text="Wallet used for investment and returns",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="investments",
                        to="wallets.wallet",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="investments",
                        to="investments.investmentproduct",
                    ),
                ),
            ],
            options={
                "db_table": "investments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InvestmentReturn",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(null=True)),
                (
                    "return_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=20)),
                ("payout_date", models.DateTimeField()),
                ("actual_payout_date", models.DateTimeField(blank=True, null=True)),
                ("is_paid", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                (
                    "investment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="returns",
                        to="investments.investment",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="investment_returns",
                        to="transactions.transaction",
                    ),
                ),
            ],
            options={
                "db_table": "investment_returns",
                "ordering": ["payout_date"],
            },
        ),
        migrations.AddIndex(
            model_name="investmentproduct",
            index=models.Index(
                fields=["product_type", "is_active"],
                name="investment__product_48fb5f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="investmentproduct",
            index=models.Index(
                fields=["currency", "is_active"], name="investment__currenc_63e87f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="investmentproduct",
            index=models.Index(
                fields=["risk_level"], name="investment__risk_le_ec311e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="investment",
            index=models.Index(
                fields=["user", "status"], name="investments_user_id_dfa5b0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="investment",
            index=models.Index(
                fields=["product", "status"], name="investments_product_831642_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="investment",
            index=models.Index(
                fields=["status", "maturity_date"], name="investments_status_ca6901_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="investment",
            index=models.Index(
                fields=["wallet", "-created_at"], name="investments_wallet__c5ba6e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="investmentreturn",
            index=models.Index(
                fields=["investment", "is_paid"], name="investment__investm_8bf455_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="investmentreturn",
            index=models.Index(
                fields=["payout_date", "is_paid"], name="investment__payout__bf7754_idx"
            ),
        ),
    ]
