# Generated by Django 5.2.6 on 2025-10-19 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("investments", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="investment",
            new_name="investments_user_id_352b49_idx",
            old_name="investments_user_id_dfa5b0_idx",
        ),
        migrations.RenameIndex(
            model_name="investment",
            new_name="investments_product_a8e087_idx",
            old_name="investments_product_831642_idx",
        ),
        migrations.RenameIndex(
            model_name="investment",
            new_name="investments_status_3737c8_idx",
            old_name="investments_status_ca6901_idx",
        ),
        migrations.RenameIndex(
            model_name="investment",
            new_name="investments_wallet__cad67b_idx",
            old_name="investments_wallet__c5ba6e_idx",
        ),
        migrations.RenameIndex(
            model_name="investmentproduct",
            new_name="investments_product_7e5d05_idx",
            old_name="investment__product_48fb5f_idx",
        ),
        migrations.RenameIndex(
            model_name="investmentproduct",
            new_name="investments_currenc_3fdcb5_idx",
            old_name="investment__currenc_63e87f_idx",
        ),
        migrations.RenameIndex(
            model_name="investmentproduct",
            new_name="investments_risk_le_ae6c99_idx",
            old_name="investment__risk_le_ec311e_idx",
        ),
        migrations.RenameIndex(
            model_name="investmentreturn",
            new_name="investments_investm_40a17d_idx",
            old_name="investment__investm_8bf455_idx",
        ),
        migrations.RenameIndex(
            model_name="investmentreturn",
            new_name="investments_payout__a13a51_idx",
            old_name="investment__payout__bf7754_idx",
        ),
        migrations.AlterModelTable(
            name="investment",
            table=None,
        ),
        migrations.AlterModelTable(
            name="investmentportfolio",
            table=None,
        ),
        migrations.AlterModelTable(
            name="investmentproduct",
            table=None,
        ),
        migrations.AlterModelTable(
            name="investmentreturn",
            table=None,
        ),
    ]
