# Generated by Django 5.2.6 on 2025-11-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "investments",
            "0002_rename_investments_user_id_dfa5b0_idx_investments_user_id_352b49_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="investment",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="investmentportfolio",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="investmentproduct",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="investmentreturn",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
