# Generated by Django 5.2.6 on 2025-10-18 23:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0001_initial"),
        ("wallets", "0005_delete_virtualcard"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutoRepayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(null=True)),
                (
                    "auto_repayment_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True, help_text="Whether auto-repayment is active"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("suspended", "Suspended"),
                            ("failed", "Failed"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "auto_pay_full_amount",
                    models.BooleanField(
                        default=True,
                        help_text="Pay full installment amount automatically",
                    ),
                ),
                (
                    "custom_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Custom amount to pay (if not full amount)",
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "days_before_due",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of days before due date to trigger payment (0 = on due date)",
                    ),
                ),
                (
                    "retry_on_failure",
                    models.BooleanField(
                        default=True,
                        help_text="Retry if payment fails due to insufficient balance",
                    ),
                ),
                (
                    "max_retry_attempts",
                    models.PositiveIntegerField(
                        default=3, help_text="Maximum number of retry attempts"
                    ),
                ),
                (
                    "retry_interval_hours",
                    models.PositiveIntegerField(
                        default=24, help_text="Hours between retry attempts"
                    ),
                ),
                (
                    "total_payments_made",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total number of automatic payments processed",
                    ),
                ),
                (
                    "last_payment_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last successful automatic payment",
                        null=True,
                    ),
                ),
                (
                    "last_payment_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Amount of last automatic payment",
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "last_failure_date",
                    models.DateTimeField(
                        blank=True, help_text="Last failed payment attempt", null=True
                    ),
                ),
                (
                    "last_failure_reason",
                    models.TextField(
                        blank=True, help_text="Reason for last failure", null=True
                    ),
                ),
                (
                    "consecutive_failures",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of consecutive failed attempts"
                    ),
                ),
                (
                    "send_notification_on_success",
                    models.BooleanField(
                        default=True,
                        help_text="Send notification when payment succeeds",
                    ),
                ),
                (
                    "send_notification_on_failure",
                    models.BooleanField(
                        default=True, help_text="Send notification when payment fails"
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="loanrepaymentschedule",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="loanrepaymentschedule",
            constraint=models.UniqueConstraint(
                fields=("loan", "installment_number"),
                name="unique_loan_installment_number",
            ),
        ),
        migrations.AddField(
            model_name="autorepayment",
            name="loan",
            field=models.OneToOneField(
                help_text="Loan to auto-repay",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="auto_repayment",
                to="loans.loanapplication",
            ),
        ),
        migrations.AddField(
            model_name="autorepayment",
            name="wallet",
            field=models.ForeignKey(
                help_text="Wallet to debit automatically",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="loan_auto_repayments",
                to="wallets.wallet",
            ),
        ),
        migrations.AddIndex(
            model_name="autorepayment",
            index=models.Index(
                fields=["loan", "status"], name="loans_autor_loan_id_78d9e9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="autorepayment",
            index=models.Index(
                fields=["is_enabled", "status"], name="loans_autor_is_enab_1d5a3a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="autorepayment",
            index=models.Index(
                fields=["wallet", "-created_at"], name="loans_autor_wallet__bdea60_idx"
            ),
        ),
    ]
