# Generated by Django 5.2.6 on 2025-11-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0002_autorepayment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autorepayment",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="creditscore",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="loanapplication",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="loanproduct",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="loanrepayment",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="loanrepaymentschedule",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
