# Generated by Django 5.2.6 on 2025-09-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="phone",
        ),
        migrations.AlterField(
            model_name="user",
            name="access",
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="refresh",
            field=models.TextField(editable=False, null=True),
        ),
    ]
