# Generated by Django 5.2.6 on 2025-09-26 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_user_phone_alter_user_access_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="biometrics_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="trust_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="trust_token_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
