# Generated by Django 5.2.6 on 2025-09-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_biometrics_enabled_user_trust_token_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="trust_token",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
