# Generated by Django 5.2.6 on 2025-10-19 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_user_trust_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_enabled",
            field=models.BooleanField(
                default=True, help_text="Receive email notifications"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="in_app_enabled",
            field=models.BooleanField(
                default=True, help_text="Receive in-app notifications"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="push_enabled",
            field=models.BooleanField(
                default=True, help_text="Receive push notifications"
            ),
        ),
    ]
