# Generated by Django 5.2.6 on 2025-11-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_user_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
