# Generated by Django 5.2.6 on 2025-10-20 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("audit_logs", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="auditlog",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="audit_logs__created_cc00f5_idx",
            old_name="audit_logs_created_43fcd6_idx",
        ),
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="audit_logs__user_id_c41764_idx",
            old_name="audit_logs_user_id_6193b2_idx",
        ),
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="audit_logs__event_t_f4b7cd_idx",
            old_name="audit_logs_event_t_d2baa2_idx",
        ),
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="audit_logs__event_c_dbb911_idx",
            old_name="audit_logs_event_c_622adb_idx",
        ),
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="audit_logs__severit_ce604a_idx",
            old_name="audit_logs_severit_a4af98_idx",
        ),
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="audit_logs__ip_addr_52c8c2_idx",
            old_name="audit_logs_ip_addr_190b84_idx",
        ),
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="audit_logs__resourc_760a22_idx",
            old_name="audit_logs_resourc_bda8a6_idx",
        ),
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="audit_logs__is_comp_a04f0b_idx",
            old_name="audit_logs_is_comp_0fb0b4_idx",
        ),
        migrations.AlterModelTable(
            name="auditlog",
            table=None,
        ),
    ]
