# Generated by Django 5.2.6 on 2025-11-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit_logs", "0002_alter_auditlog_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
