COUNTRIES_DATA = [
    {"name": "Afghanistan", "code": "AF", "currency_code": "AFN"},
    {"name": "Albania", "code": "AL", "currency_code": "ALL"},
    {"name": "Algeria", "code": "DZ", "currency_code": "DZD"},
    {"name": "Andorra", "code": "AD", "currency_code": "EUR"},
    {"name": "Angola", "code": "AO", "currency_code": "AOA"},
    {"name": "Antigua and Barbuda", "code": "AG", "currency_code": "XCD"},
    {"name": "Argentina", "code": "AR", "currency_code": "ARS"},
    {"name": "Armenia", "code": "AM", "currency_code": "AMD"},
    {"name": "Australia", "code": "AU", "currency_code": "AUD"},
    {"name": "Austria", "code": "AT", "currency_code": "EUR"},
    {"name": "Azerbaijan", "code": "AZ", "currency_code": "AZN"},
    {"name": "Bahamas", "code": "BS", "currency_code": "BSD"},
    {"name": "Bahrain", "code": "BH", "currency_code": "BHD"},
    {"name": "Bangladesh", "code": "BD", "currency_code": "BDT"},
    {"name": "Barbados", "code": "BB", "currency_code": "BBD"},
    {"name": "Belarus", "code": "BY", "currency_code": "BYN"},
    {"name": "Belgium", "code": "BE", "currency_code": "EUR"},
    {"name": "Belize", "code": "BZ", "currency_code": "BZD"},
    {"name": "Benin", "code": "BJ", "currency_code": "XOF"},
    {"name": "Bhutan", "code": "BT", "currency_code": "BTN"},
    {"name": "Bolivia", "code": "BO", "currency_code": "BOB"},
    {"name": "Bosnia and Herzegovina", "code": "BA", "currency_code": "BAM"},
    {"name": "Botswana", "code": "BW", "currency_code": "BWP"},
    {"name": "Brazil", "code": "BR", "currency_code": "BRL"},
    {"name": "Brunei", "code": "BN", "currency_code": "BND"},
    {"name": "Bulgaria", "code": "BG", "currency_code": "BGN"},
    {"name": "Burkina Faso", "code": "BF", "currency_code": "XOF"},
    {"name": "Burundi", "code": "BI", "currency_code": "BIF"},
    {"name": "Cambodia", "code": "KH", "currency_code": "KHR"},
    {"name": "Cameroon", "code": "CM", "currency_code": "XAF"},
    {"name": "Canada", "code": "CA", "currency_code": "CAD"},
    {"name": "Cape Verde", "code": "CV", "currency_code": "CVE"},
    {"name": "Central African Republic", "code": "CF", "currency_code": "XAF"},
    {"name": "Chad", "code": "TD", "currency_code": "XAF"},
    {"name": "Chile", "code": "CL", "currency_code": "CLP"},
    {"name": "China", "code": "CN", "currency_code": "CNY"},
    {"name": "Colombia", "code": "CO", "currency_code": "COP"},
    {"name": "Comoros", "code": "KM", "currency_code": "KMF"},
    {"name": "Congo (Brazzaville)", "code": "CG", "currency_code": "XAF"},
    {"name": "Congo (Kinshasa)", "code": "CD", "currency_code": "CDF"},
    {"name": "Costa Rica", "code": "CR", "currency_code": "CRC"},
    {"name": "Croatia", "code": "HR", "currency_code": "EUR"},
    {"name": "Cuba", "code": "CU", "currency_code": "CUP"},
    {"name": "Cyprus", "code": "CY", "currency_code": "EUR"},
    {"name": "Czech Republic", "code": "CZ", "currency_code": "CZK"},
    {"name": "Denmark", "code": "DK", "currency_code": "DKK"},
    {"name": "Djibouti", "code": "DJ", "currency_code": "DJF"},
    {"name": "Dominica", "code": "DM", "currency_code": "XCD"},
    {"name": "Dominican Republic", "code": "DO", "currency_code": "DOP"},
    {"name": "Ecuador", "code": "EC", "currency_code": "USD"},
    {"name": "Egypt", "code": "EG", "currency_code": "EGP"},
    {"name": "El Salvador", "code": "SV", "currency_code": "USD"},
    {"name": "Equatorial Guinea", "code": "GQ", "currency_code": "XAF"},
    {"name": "Eritrea", "code": "ER", "currency_code": "ERN"},
    {"name": "Estonia", "code": "EE", "currency_code": "EUR"},
    {"name": "Eswatini", "code": "SZ", "currency_code": "SZL"},
    {"name": "Ethiopia", "code": "ET", "currency_code": "ETB"},
    {"name": "Fiji", "code": "FJ", "currency_code": "FJD"},
    {"name": "Finland", "code": "FI", "currency_code": "EUR"},
    {"name": "France", "code": "FR", "currency_code": "EUR"},
    {"name": "Gabon", "code": "GA", "currency_code": "XAF"},
    {"name": "Gambia", "code": "GM", "currency_code": "GMD"},
    {"name": "Georgia", "code": "GE", "currency_code": "GEL"},
    {"name": "Germany", "code": "DE", "currency_code": "EUR"},
    {"name": "Ghana", "code": "GH", "currency_code": "GHS"},
    {"name": "Greece", "code": "GR", "currency_code": "EUR"},
    {"name": "Grenada", "code": "GD", "currency_code": "XCD"},
    {"name": "Guatemala", "code": "GT", "currency_code": "GTQ"},
    {"name": "Guinea", "code": "GN", "currency_code": "GNF"},
    {"name": "Guinea-Bissau", "code": "GW", "currency_code": "XOF"},
    {"name": "Guyana", "code": "GY", "currency_code": "GYD"},
    {"name": "Haiti", "code": "HT", "currency_code": "HTG"},
    {"name": "Honduras", "code": "HN", "currency_code": "HNL"},
    {"name": "Hungary", "code": "HU", "currency_code": "HUF"},
    {"name": "Iceland", "code": "IS", "currency_code": "ISK"},
    {"name": "India", "code": "IN", "currency_code": "INR"},
    {"name": "Indonesia", "code": "ID", "currency_code": "IDR"},
    {"name": "Iran", "code": "IR", "currency_code": "IRR"},
    {"name": "Iraq", "code": "IQ", "currency_code": "IQD"},
    {"name": "Ireland", "code": "IE", "currency_code": "EUR"},
    {"name": "Israel", "code": "IL", "currency_code": "ILS"},
    {"name": "Italy", "code": "IT", "currency_code": "EUR"},
    {"name": "Ivory Coast", "code": "CI", "currency_code": "XOF"},
    {"name": "Jamaica", "code": "JM", "currency_code": "JMD"},
    {"name": "Japan", "code": "JP", "currency_code": "JPY"},
    {"name": "Jordan", "code": "JO", "currency_code": "JOD"},
    {"name": "Kazakhstan", "code": "KZ", "currency_code": "KZT"},
    {"name": "Kenya", "code": "KE", "currency_code": "KES"},
    {"name": "Kiribati", "code": "KI", "currency_code": "AUD"},
    {"name": "Kosovo", "code": "XK", "currency_code": "EUR"},
    {"name": "Kuwait", "code": "KW", "currency_code": "KWD"},
    {"name": "Kyrgyzstan", "code": "KG", "currency_code": "KGS"},
    {"name": "Laos", "code": "LA", "currency_code": "LAK"},
    {"name": "Latvia", "code": "LV", "currency_code": "EUR"},
    {"name": "Lebanon", "code": "LB", "currency_code": "LBP"},
    {"name": "Lesotho", "code": "LS", "currency_code": "LSL"},
    {"name": "Liberia", "code": "LR", "currency_code": "LRD"},
    {"name": "Libya", "code": "LY", "currency_code": "LYD"},
    {"name": "Liechtenstein", "code": "LI", "currency_code": "CHF"},
    {"name": "Lithuania", "code": "LT", "currency_code": "EUR"},
    {"name": "Luxembourg", "code": "LU", "currency_code": "EUR"},
    {"name": "Madagascar", "code": "MG", "currency_code": "MGA"},
    {"name": "Malawi", "code": "MW", "currency_code": "MWK"},
    {"name": "Malaysia", "code": "MY", "currency_code": "MYR"},
    {"name": "Maldives", "code": "MV", "currency_code": "MVR"},
    {"name": "Mali", "code": "ML", "currency_code": "XOF"},
    {"name": "Malta", "code": "MT", "currency_code": "EUR"},
    {"name": "Marshall Islands", "code": "MH", "currency_code": "USD"},
    {"name": "Mauritania", "code": "MR", "currency_code": "MRU"},
    {"name": "Mauritius", "code": "MU", "currency_code": "MUR"},
    {"name": "Mexico", "code": "MX", "currency_code": "MXN"},
    {"name": "Micronesia", "code": "FM", "currency_code": "USD"},
    {"name": "Moldova", "code": "MD", "currency_code": "MDL"},
    {"name": "Monaco", "code": "MC", "currency_code": "EUR"},
    {"name": "Mongolia", "code": "MN", "currency_code": "MNT"},
    {"name": "Montenegro", "code": "ME", "currency_code": "EUR"},
    {"name": "Morocco", "code": "MA", "currency_code": "MAD"},
    {"name": "Mozambique", "code": "MZ", "currency_code": "MZN"},
    {"name": "Myanmar", "code": "MM", "currency_code": "MMK"},
    {"name": "Namibia", "code": "NA", "currency_code": "NAD"},
    {"name": "Nauru", "code": "NR", "currency_code": "AUD"},
    {"name": "Nepal", "code": "NP", "currency_code": "NPR"},
    {"name": "Netherlands", "code": "NL", "currency_code": "EUR"},
    {"name": "New Zealand", "code": "NZ", "currency_code": "NZD"},
    {"name": "Nicaragua", "code": "NI", "currency_code": "NIO"},
    {"name": "Niger", "code": "NE", "currency_code": "XOF"},
    {"name": "Nigeria", "code": "NG", "currency_code": "NGN"},
    {"name": "North Korea", "code": "KP", "currency_code": "KPW"},
    {"name": "North Macedonia", "code": "MK", "currency_code": "MKD"},
    {"name": "Norway", "code": "NO", "currency_code": "NOK"},
    {"name": "Oman", "code": "OM", "currency_code": "OMR"},
    {"name": "Pakistan", "code": "PK", "currency_code": "PKR"},
    {"name": "Palau", "code": "PW", "currency_code": "USD"},
    {"name": "Palestine", "code": "PS", "currency_code": "ILS"},
    {"name": "Panama", "code": "PA", "currency_code": "PAB"},
    {"name": "Papua New Guinea", "code": "PG", "currency_code": "PGK"},
    {"name": "Paraguay", "code": "PY", "currency_code": "PYG"},
    {"name": "Peru", "code": "PE", "currency_code": "PEN"},
    {"name": "Philippines", "code": "PH", "currency_code": "PHP"},
    {"name": "Poland", "code": "PL", "currency_code": "PLN"},
    {"name": "Portugal", "code": "PT", "currency_code": "EUR"},
    {"name": "Qatar", "code": "QA", "currency_code": "QAR"},
    {"name": "Romania", "code": "RO", "currency_code": "RON"},
    {"name": "Russia", "code": "RU", "currency_code": "RUB"},
    {"name": "Rwanda", "code": "RW", "currency_code": "RWF"},
    {"name": "Saint Kitts and Nevis", "code": "KN", "currency_code": "XCD"},
    {"name": "Saint Lucia", "code": "LC", "currency_code": "XCD"},
    {"name": "Saint Vincent and the Grenadines", "code": "VC", "currency_code": "XCD"},
    {"name": "Samoa", "code": "WS", "currency_code": "WST"},
    {"name": "San Marino", "code": "SM", "currency_code": "EUR"},
    {"name": "Sao Tome and Principe", "code": "ST", "currency_code": "STN"},
    {"name": "Saudi Arabia", "code": "SA", "currency_code": "SAR"},
    {"name": "Senegal", "code": "SN", "currency_code": "XOF"},
    {"name": "Serbia", "code": "RS", "currency_code": "RSD"},
    {"name": "Seychelles", "code": "SC", "currency_code": "SCR"},
    {"name": "Sierra Leone", "code": "SL", "currency_code": "SLL"},
    {"name": "Singapore", "code": "SG", "currency_code": "SGD"},
    {"name": "Slovakia", "code": "SK", "currency_code": "EUR"},
    {"name": "Slovenia", "code": "SI", "currency_code": "EUR"},
    {"name": "Solomon Islands", "code": "SB", "currency_code": "SBD"},
    {"name": "Somalia", "code": "SO", "currency_code": "SOS"},
    {"name": "South Africa", "code": "ZA", "currency_code": "ZAR"},
    {"name": "South Korea", "code": "KR", "currency_code": "KRW"},
    {"name": "South Sudan", "code": "SS", "currency_code": "SSP"},
    {"name": "Spain", "code": "ES", "currency_code": "EUR"},
    {"name": "Sri Lanka", "code": "LK", "currency_code": "LKR"},
    {"name": "Sudan", "code": "SD", "currency_code": "SDG"},
    {"name": "Suriname", "code": "SR", "currency_code": "SRD"},
    {"name": "Sweden", "code": "SE", "currency_code": "SEK"},
    {"name": "Switzerland", "code": "CH", "currency_code": "CHF"},
    {"name": "Syria", "code": "SY", "currency_code": "SYP"},
    {"name": "Taiwan", "code": "TW", "currency_code": "TWD"},
    {"name": "Tajikistan", "code": "TJ", "currency_code": "TJS"},
    {"name": "Tanzania", "code": "TZ", "currency_code": "TZS"},
    {"name": "Thailand", "code": "TH", "currency_code": "THB"},
    {"name": "Timor-Leste", "code": "TL", "currency_code": "USD"},
    {"name": "Togo", "code": "TG", "currency_code": "XOF"},
    {"name": "Tonga", "code": "TO", "currency_code": "TOP"},
    {"name": "Trinidad and Tobago", "code": "TT", "currency_code": "TTD"},
    {"name": "Tunisia", "code": "TN", "currency_code": "TND"},
    {"name": "Turkey", "code": "TR", "currency_code": "TRY"},
    {"name": "Turkmenistan", "code": "TM", "currency_code": "TMT"},
    {"name": "Tuvalu", "code": "TV", "currency_code": "AUD"},
    {"name": "Uganda", "code": "UG", "currency_code": "UGX"},
    {"name": "Ukraine", "code": "UA", "currency_code": "UAH"},
    {"name": "United Arab Emirates", "code": "AE", "currency_code": "AED"},
    {"name": "United Kingdom", "code": "GB", "currency_code": "GBP"},
    {"name": "United States", "code": "US", "currency_code": "USD"},
    {"name": "Uruguay", "code": "UY", "currency_code": "UYU"},
    {"name": "Uzbekistan", "code": "UZ", "currency_code": "UZS"},
    {"name": "Vanuatu", "code": "VU", "currency_code": "VUV"},
    {"name": "Vatican City", "code": "VA", "currency_code": "EUR"},
    {"name": "Venezuela", "code": "VE", "currency_code": "VES"},
    {"name": "Vietnam", "code": "VN", "currency_code": "VND"},
    {"name": "Yemen", "code": "YE", "currency_code": "YER"},
    {"name": "Zambia", "code": "ZM", "currency_code": "ZMW"},
    {"name": "Zimbabwe", "code": "ZW", "currency_code": "ZWL"},
]
