# Generated by Django 5.2.6 on 2025-10-10 12:21

import autoslug.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("transactions", "0005_alter_transaction_transaction_type"),
        ("wallets", "0005_delete_virtualcard"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BillProvider",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(null=True)),
                (
                    "provider_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        max_length=100,
                        populate_from="name",
                        unique=True,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("airtime", "Airtime Recharge"),
                            ("data", "Data Bundle"),
                            ("electricity", "Electricity Bill"),
                            ("cable_tv", "Cable TV Subscription"),
                            ("internet", "Internet Service"),
                            ("water", "Water Bill"),
                            ("waste", "Waste Management"),
                            ("education", "Education/School Fees"),
                            ("government", "Government Services"),
                            ("insurance", "Insurance Premium"),
                            ("tax", "Tax Payment"),
                            ("other", "Other Bills"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "provider_code",
                    models.CharField(
                        help_text="Code used by payment gateway",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_available",
                    models.BooleanField(
                        default=True, help_text="Temporarily unavailable"
                    ),
                ),
                ("logo_url", models.URLField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "supports_amount_range",
                    models.BooleanField(
                        default=False, help_text="User can enter custom amount"
                    ),
                ),
                (
                    "min_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "max_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "fee_type",
                    models.CharField(
                        choices=[
                            ("flat", "Flat Fee"),
                            ("percentage", "Percentage"),
                            ("none", "No Fee"),
                        ],
                        default="flat",
                        max_length=20,
                    ),
                ),
                (
                    "fee_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "fee_cap",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum fee amount",
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "requires_customer_validation",
                    models.BooleanField(
                        default=False, help_text="Validate customer before payment"
                    ),
                ),
                (
                    "validation_fields",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Required fields for validation",
                    ),
                ),
                (
                    "extra_fields",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional fields required"
                    ),
                ),
            ],
            options={
                "ordering": ["category", "name"],
                "indexes": [
                    models.Index(
                        fields=["category", "is_active"],
                        name="bills_billp_categor_354203_idx",
                    ),
                    models.Index(
                        fields=["provider_code"], name="bills_billp_provide_934464_idx"
                    ),
                    models.Index(fields=["slug"], name="bills_billp_slug_c46a1a_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="BillPackage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(null=True)),
                (
                    "package_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "code",
                    models.CharField(
                        help_text="Package code from provider", max_length=100
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=20)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "validity_period",
                    models.CharField(
                        blank=True,
                        help_text="e.g., '30 days', '1 month'",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "benefits",
                    models.JSONField(
                        blank=True, default=list, help_text="List of package benefits"
                    ),
                ),
                ("is_popular", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.IntegerField(default=0)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="packages",
                        to="bills.billprovider",
                    ),
                ),
            ],
            options={
                "ordering": ["provider", "display_order", "amount"],
            },
        ),
        migrations.CreateModel(
            name="BillBeneficiary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(null=True)),
                (
                    "beneficiary_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "nickname",
                    models.CharField(
                        help_text="User-friendly name (e.g., 'Home Electricity')",
                        max_length=100,
                    ),
                ),
                ("customer_id", models.CharField(max_length=200)),
                (
                    "customer_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("usage_count", models.IntegerField(default=0)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("extra_data", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bill_beneficiaries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="beneficiaries",
                        to="bills.billprovider",
                    ),
                ),
            ],
            options={
                "ordering": ["-last_used_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BillPaymentSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(null=True)),
                (
                    "schedule_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("customer_id", models.CharField(max_length=200)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                        ],
                        max_length=20,
                    ),
                ),
                ("next_payment_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                ("is_paused", models.BooleanField(default=False)),
                ("total_payments", models.IntegerField(default=0)),
                ("successful_payments", models.IntegerField(default=0)),
                ("failed_payments", models.IntegerField(default=0)),
                ("last_payment_date", models.DateField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("extra_data", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bill_schedules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bill_schedules",
                        to="wallets.wallet",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="bills.billprovider",
                    ),
                ),
            ],
            options={
                "ordering": ["next_payment_date"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="bills_billp_user_id_fb4feb_idx",
                    ),
                    models.Index(
                        fields=["next_payment_date", "is_active"],
                        name="bills_billp_next_pa_f471cb_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="BillPayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(null=True)),
                (
                    "payment_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("airtime", "Airtime Recharge"),
                            ("data", "Data Bundle"),
                            ("electricity", "Electricity Bill"),
                            ("cable_tv", "Cable TV Subscription"),
                            ("internet", "Internet Service"),
                            ("water", "Water Bill"),
                            ("waste", "Waste Management"),
                            ("education", "Education/School Fees"),
                            ("government", "Government Services"),
                            ("insurance", "Insurance Premium"),
                            ("tax", "Tax Payment"),
                            ("other", "Other Bills"),
                        ],
                        max_length=50,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "fee_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "customer_id",
                    models.CharField(
                        help_text="Customer ID/Number (meter number, phone, smartcard)",
                        max_length=200,
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "customer_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "customer_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("reversed", "Reversed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "provider_reference",
                    models.CharField(
                        blank=True, db_index=True, max_length=200, null=True
                    ),
                ),
                ("provider_response", models.JSONField(blank=True, default=dict)),
                ("token", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "token_units",
                    models.CharField(
                        blank=True,
                        help_text="Units purchased (kWh, GB, etc.)",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "extra_data",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional payment data"
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                ("failure_reason", models.TextField(blank=True, null=True)),
                ("save_beneficiary", models.BooleanField(default=False)),
                (
                    "package",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="bills.billpackage",
                    ),
                ),
                (
                    "transaction",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bill_payment",
                        to="transactions.transaction",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bill_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bill_payments",
                        to="wallets.wallet",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="bills.billprovider",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="bills_billp_user_id_1950eb_idx",
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="bills_billp_status_9af267_idx",
                    ),
                    models.Index(
                        fields=["category", "-created_at"],
                        name="bills_billp_categor_b32068_idx",
                    ),
                    models.Index(
                        fields=["provider", "-created_at"],
                        name="bills_billp_provide_2fade8_idx",
                    ),
                    models.Index(
                        fields=["provider_reference"],
                        name="bills_billp_provide_5ad704_idx",
                    ),
                    models.Index(
                        fields=["customer_id"], name="bills_billp_custome_708656_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="billpackage",
            index=models.Index(
                fields=["provider", "is_active"], name="bills_billp_provide_592a56_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="billpackage",
            index=models.Index(fields=["code"], name="bills_billp_code_d2d70e_idx"),
        ),
        migrations.AddConstraint(
            model_name="billpackage",
            constraint=models.UniqueConstraint(
                fields=("provider", "code"), name="unique_package_provider_code"
            ),
        ),
        migrations.AddIndex(
            model_name="billbeneficiary",
            index=models.Index(
                fields=["user", "-last_used_at"], name="bills_billb_user_id_1c4759_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="billbeneficiary",
            index=models.Index(
                fields=["user", "provider"], name="bills_billb_user_id_d2aee8_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="billbeneficiary",
            constraint=models.UniqueConstraint(
                fields=("user", "provider", "customer_id"),
                name="unique_user_provider_customer_beneficiary",
            ),
        ),
    ]
