# Generated by Django 5.2.6 on 2025-11-01 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bills", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billpayment",
            name="extra_data",
            field=models.JSONField(
                blank=True, default=dict, help_text="Additional payment data", null=True
            ),
        ),
    ]
