# Generated by Django 5.2.6 on 2025-11-01 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bills", "0002_alter_billpayment_extra_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billpayment",
            name="provider_response",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
