# Generated by Django 5.2.6 on 2025-11-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bills", "0003_alter_billpayment_provider_response"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billbeneficiary",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="billpackage",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="billpayment",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="billpaymentschedule",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="billprovider",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
