# Generated by Django 6.0 on 2026-01-12 17:06

import apps.common.models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiometricCredential',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('credential_id', models.BinaryField(help_text='The Credential ID generated by the authenticator.', unique=True)),
                ('public_key', models.BinaryField(help_text='The Public Key for signature verification.')),
                ('sign_count', models.IntegerField(default=0, help_text='Counter to prevent replay attacks.')),
                ('device_name', models.CharField(blank=True, help_text="User-friendly name (e.g., 'MacBook TouchID').", max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Biometric Credential',
                'verbose_name_plural': 'Biometric Credentials',
            },
        ),
        migrations.CreateModel(
            name='UnifiedUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Flag indicating if the record is soft-deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp of soft deletion.', null=True)),
                ('email', models.EmailField(blank=True, db_index=True, help_text='Primary unique identifier for email-based auth.', max_length=254, null=True, unique=True, verbose_name='email address')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, db_index=True, help_text='Primary unique identifier for phone-based auth.', max_length=128, null=True, region=None, unique=True)),
                ('avatar', models.ImageField(default='default/default-user.jpg', help_text="User's profile picture.", upload_to='avatars/%Y/%m/')),
                ('bio', models.TextField(blank=True, help_text="User's biography.")),
                ('country', models.CharField(blank=True, db_index=True, help_text="User's country.", max_length=100)),
                ('state', models.CharField(blank=True, help_text="User's state.", max_length=100)),
                ('city', models.CharField(blank=True, help_text="User's city.", max_length=100)),
                ('address', models.CharField(blank=True, help_text="User's address.", max_length=255)),
                ('role', models.CharField(choices=[('vendor', 'Vendor'), ('client', 'Client'), ('staff', 'Staff'), ('admin', 'Admin'), ('editor', 'Editor'), ('support', 'Support'), ('assistant', 'Assistant')], db_index=True, default='client', help_text='RBAC Role. Cannot be changed after creation easily.', max_length=20)),
                ('auth_provider', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('google', 'Google')], default='email', help_text='Authentication provider used.', max_length=20)),
                ('is_verified', models.BooleanField(db_index=True, default=False, help_text='True if email/phone OTP is verified.')),
                ('pid', models.CharField(help_text='Unique identifier.', max_length=50, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Unified User',
                'verbose_name_plural': 'Unified Users',
            },
            bases=(models.Model, apps.common.models.HardDeleteMixin),
        ),
        migrations.RemoveIndex(
            model_name='profile',
            name='auth_temp_profile_user_idx',
        ),
        migrations.RemoveIndex(
            model_name='profile',
            name='auth_temp_profile_name_idx',
        ),
        migrations.RemoveIndex(
            model_name='profile',
            name='auth_temp_profile_email_idx',
        ),
        migrations.RemoveIndex(
            model_name='profile',
            name='auth_temp_profile_phone_idx',
        ),
        migrations.RemoveIndex(
            model_name='profile',
            name='auth_temp_profile_cntry_idx',
        ),
        migrations.RemoveIndex(
            model_name='profile',
            name='auth_temp_profile_state_idx',
        ),
        migrations.RemoveIndex(
            model_name='profile',
            name='auth_temp_profile_city_idx',
        ),
        migrations.RemoveIndex(
            model_name='profile',
            name='auth_temp_prof_cntry_st_idx',
        ),
        migrations.RemoveIndex(
            model_name='profile',
            name='auth_temp_prof_cntry_ct_idx',
        ),
        migrations.RemoveIndex(
            model_name='profile',
            name='auth_temp_prof_st_ct_idx',
        ),
        migrations.RemoveIndex(
            model_name='profile',
            name='auth_temp_prof_usr_nam_idx',
        ),
        migrations.RemoveIndex(
            model_name='tokens',
            name='auth_temp_tokens_email_idx',
        ),
        migrations.RemoveIndex(
            model_name='tokens',
            name='auth_temp_tokens_phone_idx',
        ),
        migrations.RemoveIndex(
            model_name='tokens',
            name='auth_temp_tokens_token_idx',
        ),
        migrations.DeleteModel(
            name='Tokens',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='auth_temp_user_email_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='auth_temp_user_phone_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='auth_temp_user_email_pass_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='auth_temp_user_phone_pass_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='auth_temp_user_role_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='auth_temp_user_verified_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='auth_temp_user_is_active_idx',
        ),
        migrations.AddField(
            model_name='unifieduser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='unified_user_set', related_query_name='unified_user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='unifieduser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='unified_user_set', related_query_name='unified_user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='biometriccredential',
            name='user',
            field=models.ForeignKey(help_text='The user this credential belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='biometric_credentials', to='authentication.unifieduser'),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='deliveryContact',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='measurement',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='shippingAddress',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.AddIndex(
            model_name='unifieduser',
            index=models.Index(fields=['email', 'role'], name='authenticat_email_19147e_idx'),
        ),
        migrations.AddIndex(
            model_name='unifieduser',
            index=models.Index(fields=['phone', 'role'], name='authenticat_phone_532574_idx'),
        ),
        migrations.AddIndex(
            model_name='unifieduser',
            index=models.Index(fields=['auth_provider', 'is_verified'], name='authenticat_auth_pr_c6d242_idx'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
