# Generated by Django 5.2.6 on 2025-09-28 20:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="wallet",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="wallet",
            constraint=models.UniqueConstraint(
                fields=("user", "currency", "is_default"),
                name="unique_default_wallet_per_currency",
            ),
        ),
    ]
