# Generated by Django 5.2.6 on 2025-09-28 21:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0002_alter_wallet_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="wallet",
            name="unique_default_wallet_per_currency",
        ),
        migrations.AddConstraint(
            model_name="wallet",
            constraint=models.UniqueConstraint(
                fields=("user", "currency", "wallet_type", "is_default"),
                name="unique_default_wallet_per_currency",
            ),
        ),
    ]
