# Generated by Django 5.2.6 on 2025-10-04 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0003_remove_wallet_unique_default_wallet_per_currency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="account_name",
            field=models.CharField(
                blank=True,
                help_text="Account holder name (usually user's full name)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="wallet",
            name="account_number",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Unique account number for receiving deposits (auto-generated for main wallets)",
                max_length=20,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="wallet",
            name="account_provider",
            field=models.CharField(
                choices=[
                    ("internal", "Internal"),
                    ("paystack", "Paystack"),
                    ("flutterwave", "Flutterwave"),
                    ("wise", "Wise"),
                ],
                default="internal",
                help_text="Provider managing this account (internal, paystack, flutterwave, wise)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="wallet",
            name="bank_name",
            field=models.CharField(
                default="PayCore",
                help_text="Bank name shown for this account",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="wallet",
            name="is_test_mode",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if this account is in test/sandbox mode",
            ),
        ),
        migrations.AddField(
            model_name="wallet",
            name="provider_account_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="External provider's account ID reference",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="wallet",
            name="provider_metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Provider-specific metadata and configuration",
            ),
        ),
    ]
