# Generated by Django 5.2.6 on 2025-10-04 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0004_wallet_account_name_wallet_account_number_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="VirtualCard",
        ),
    ]
